# Generated by Django 3.1.3 on 2021-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('sweater', 'Sweater'), ('sweatshirt', 'Sweatshirt'), ('jacket', 'Jacket'), ('jeans', 'Jeans'), ('leggings', 'Leggings'), ('shorts', 'Shorts')], default='tshirt', max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blu', 'Blue'), ('ylw', 'Yellow'), ('grn', 'Green'), ('brn', 'Brown')], default='red', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('time', models.IntegerField(verbose_name='Hours Played')),
            ],
        ),
    ]
