# Generated by Django 3.1.3 on 2021-01-31 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('sweater', 'Sweater'), ('sweatshirt', 'Sweatshirt'), ('jacket', 'Jacket'), ('jeans', 'Jeans'), ('leggings', 'Leggings'), ('shorts', 'Shorts')], default='tshirt', max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blu', 'Blue'), ('ylw', 'Yellow'), ('grn', 'Green'), ('brn', 'Brown')], default='red', max_length=3)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='spring', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
