# Generated by Django 3.1.3 on 2021-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210201_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(choices=[('Pink', 'Pink'), ('Red', 'Red'), ('Orange', 'Orange'), ('Beige', 'Beige'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Light Blue', 'Light Blue'), ('Dark Blue', 'Dark Blue'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Grey', 'Grey')], default='Pink', max_length=10),
        ),
    ]
