# Generated by Django 3.1.3 on 2021-02-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210201_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
