# Generated by Django 3.1.3 on 2021-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Sweater', 'Sweater'), ('Sweatshirt', 'Sweatshirt'), ('Jacket', 'Jacket'), ('Jeans', 'Jeans'), ('Leggings', 'Leggings'), ('Shorts', 'Shorts'), ('Dress Pants', 'Dress Pants'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Blouse', 'Blouse'), ('Parka', 'Parka'), ('Coat', 'Coat'), ('Tank Top', 'Tank Top')], default='T-Shirt', max_length=20),
        ),
    ]
